apiVersion: v1
kind: Service
metadata:
  name: kanban-service
  labels:
    app: kanban-pod
spec:
  type: LoadBalancer
  selector:
    app: kanban-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80