apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-pod
spec:
  replicas: 2
  strategy:
    type: Recreate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kanban-pod
  template:
    metadata:
      labels:
        app: kanban-pod
    spec:
      containers:
        - name: kanban-app
          image: nukkunda/kanban:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
