apiVersion: v1
kind: Service
metadata:
  name: kanban-service
spec:
  type: NodePort
  selector:
    app: kanban-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30003